version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tox_admin
      POSTGRES_PASSWORD: stpauli123
      POSTGRES_DB: quotes_db

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://tox_admin:stpauli123@db:5432/quotes_db
    depends_on:
      - db
    